[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

build_src_filter = -<main.cpp> -<test_case.cpp> -<new_case.cpp> -<main_new2.cpp> +<main_new.cpp> +<arm.cpp> +<input.cpp> +<protocol.cpp> +<web_ui.cpp>

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
    SPI

lib_ldf_mode = chain+

lib_ignore =
    AsyncTCP_RP2040W
    Async TCP
    ESP Async WebServer

