[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

build_src_filter = -<main.cpp> -<test_case.cpp> -<new_case.cpp> +<main_new.cpp>

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    links2004/WebSockets@^2.4.1
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git

lib_ignore =
    AsyncTCP_RP2040W
    Async TCP
    ESP Async WebServer

